services:
  app:
    build: .
    ports:
      - '5000:5000'
    environment:
      - PORT=5000
      - MONGO_URI=mongodb://mongo:27017/exchange_monitor
      - EMAIL=$${process.env.EMAIL}
      - EMAIL_PASSWORD=$${process.env.EMAIL_PASSWORD}
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
